#Swag Labs Test Data Properties File

# Application URL given byn  Developers
build1Url=https://www.saucedemo.com/

# Locators for Swag Labs Application
SwagUserNameID=user-name
SwagPasswordID=password
SwagLoginButtonID=login-button

# Test Data for Swag Labs Application
#SwagUsername=standard_user
SwagUsername=Krishna123
SwagPassword=secret_sauce

